
---
include:

# Hillside 46
#   Comment out below if you do not have this board, to save build time
  - board: nice_nano
    shield: trackball_hs
    snippet: zmk-usb-logging
    artifact-name: trackball_hs
  - board: nice_nano
    shield: settings_reset
    artifact-name: trackball_bt_reset
