
---
include:

# Trackball
  - board: nice_nano
    shield: trackball_hs
    snippet: zmk-usb-logging
    artifact-name: trackball_hs
  - board: nice_nano
    shield: settings_reset
    artifact-name: trackball_bt_reset
